Fix Build

diff --git a/.forgejo/workflows/sonar-scan.yml b/.forgejo/workflows/sonar-scan.yml
--- a/.forgejo/workflows/sonar-scan.yml
+++ b/.forgejo/workflows/sonar-scan.yml
@@ -14,6 +14,16 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Docker Cleanup
+        run: |
+          if command -v docker >/dev/null 2>&1; then
+            echo "Stopping and removing all Docker containers..."
+            docker stop $(docker ps -aq) || true
+            docker rm $(docker ps -aq) || true
+          else
+            echo "Docker not found, skipping cleanup."
+          fi
+
       - name: Checkout Code
         uses: actions/checkout@v4
 
